spring:
  datasource:
    url: jdbc:h2:mem:chronos_test_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  
chronos:
  scheduler:
    enabled: false # Disable scheduler for integration tests to avoid background noise
    worker:
      queue-name: test-queue
